#ifndef HEXCODES_H
#define HEXCODES_H

#define COLOR_BLACK_DARK_BLUE 		0x01
#define COLOR_BLACK_DARK_GREEN 		0x02
#define COLOR_BLACK_DARK_AQUA		0x03
#define COLOR_BLACK_DARK_RED		0x04
#define COLOR_BLACK_DARK_PURPLE		0x05
#define COLOR_BLACK_DARK_ORANGE		0x06
#define COLOR_BLACK_LIGHT_GRAY		0x07
#define COLOR_BLACK_DARK_GRAY		0x08
#define COLOR_BLACK_LIGHT_BLUE		0x09
#define COLOR_BLACK_LIGHT_GREEN		0x0a
#define COLOR_BLACK_LIGHT_AQUA		0x0b
#define COLOR_BLACK_LIGHT_RED		0x0c
#define COLOR_BLACK_LIGHT_PURPLE	0x0d
#define COLOR_BLACK_LIGHT_YELLOW	0x0e
#define COLOR_BLACK_WHITE			0x0f

#define COLOR_WHITE_BLACK			0xf0

#define COLOR_LIGHT_GREEN_BLACK		0xa0

#define KEY_UP		0x48
#define KEY_DOWN	0x50
// #define KEY_LEFT
// #define KEY_RIGHT
#define KEY_ENTER	0x1c

#endif